name: Deploy Django to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: "just-a-placeholder"

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            # Instalar Docker y git si no existen
            if ! command -v docker &> /dev/null
            then
              sudo yum update -y || sudo apt-get update -y
              sudo yum install -y docker || sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            if ! command -v git &> /dev/null
            then
              sudo yum install -y git || sudo apt-get install -y git
            fi

            mkdir -p /home/ec2-user/api
            cd /home/ec2-user/api

            sudo docker stop mybank_container || true
            sudo docker rm mybank_container || true
            sudo docker rmi mybank_image || true

            if [ ! -d \".git\" ]; then
              git clone https://github.com/Nicovt0/test.git .
            else
              git pull origin main
            fi

            # Verifica si requerimientos.txt existe antes de build
            if [ ! -f requerimientos.txt ]; then
              echo 'ERROR: requerimientos.txt no está en el repo/clonado. El build fallará.'
              exit 1
            fi

            sudo docker build -t mybank_image .
            sudo docker run -d \
              --name mybank_container \
              -p 80:8000 \
              --restart unless-stopped \
              mybank_image
          "